[workspace]
resolver = "2"
members = [
    "crates/gus-broker",
    "crates/gus-core",
    "crates/gus-profile",
]
default-members = [
    "crates/gus-broker",
    "crates/gus-core",
    "crates/gus-profile",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
authors = ["Naoya Takenaka <noy@abc-net.jp>"]
repository = "https://github.com/0xNOY/gus"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = "deny"
pedantic = "warn"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
toml = "0.9"
tempfile = "3.20"
sha2 = "0.10"
